// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a;

#nullable disable

namespace MIS3033_002_HW3_AbigailPidgeon.Migrations
{
    [DbContext(typeof(ReceiptDB))]
    [Migration("20230922194818_createdb")]
    partial class createdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("a.Receipt", b =>
                {
                    b.Property<string>("ReceiptID")
                        .HasColumnType("TEXT");

                    b.Property<int>("CogQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GearQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.HasKey("ReceiptID");

                    b.ToTable("ReceiptTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
